"""add risk scoring and ai analysis to audit events

Revision ID: a88f18d2cd88
Revises: 20b7925988c3
Create Date: 2026-10-01 05:32:34.564473
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a88f18d2cd88'
down_revision: Union[str, None] = '20b7925988c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('policy_decision', sa.String(length=10), nullable=True))
    op.add_column('audit_events', sa.Column('risk_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('audit_events', sa.Column('risk_level', sa.String(length=10), server_default='low', nullable=False))
    op.add_column('audit_events', sa.Column('risk_signals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('audit_events', sa.Column('ai_status', sa.String(length=15), server_default='skipped', nullable=False))
    op.add_column('audit_events', sa.Column('ai_analysis', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.add_column('audit_events', sa.Column('analysis_fingerprint', sa.String(length=64), nullable=True))
    op.create_index('ix_audit_events_agent_id_created_at', 'audit_events', ['agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_analysis_fingerprint'), 'audit_events', ['analysis_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_analysis_fingerprint'), table_name='audit_events')
    op.drop_index('ix_audit_events_agent_id_created_at', table_name='audit_events')
    op.drop_column('audit_events', 'analysis_fingerprint')
    op.drop_column('audit_events', 'ai_analysis')
    op.drop_column('audit_events', 'ai_status')
    op.drop_column('audit_events', 'risk_signals')
    op.drop_column('audit_events', 'risk_level')
    op.drop_column('audit_events', 'risk_score')
    op.drop_column('audit_events', 'policy_decision')
    # ### end Alembic commands ###